# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/APCSP2',
                'doc_host': 'https://syeung2.github.io',
                'git_url': 'https://github.com/syeung2/APCSP2',
                'lib_path': 'APCSP2'},
  'syms': {'APCSP2.core': {'APCSP2.core.foo': ('core.html#foo', 'APCSP2/core.py')}}}
