project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
    - text: "Blog"
      href: blog/index.qmd
    right:
    - text: "Schedule"
      href: schedule/index.qmd
    - text: "AP Standards"
      href: ap/index.qmd
    - text: "CTE Standards"
      href: cte/index.qmd
  sidebar:
    style: floating


metadata-files: [nbdev.yml]